### ISSUE TITLE
[Question 🤔] Use default arguments instead of short circuiting or conditionals

### ISSUE THREAD

**Issue by FacerAin** [EarthCodingLab/clean-code-python#5]
Use default arguments instead of short circuiting or conditionals

해당 문장을 어떻게 번역하면 좋을지 궁금합니다.

default arguments -> ???

short circuiting or conditionals -> ???

**Comment by kyc3492** [comment]
https://www.geeksforgeeks.org/short-circuiting-techniques-python/

위 링크를 확인했을 때에는 `short-circuiting` 을 결국 `boolean을 활용한 함수 중단`이라고 해석할 수 있을 것 같습니다. (사전적으로 "단선" 이라던데 "쇼트났다"가 이 말인가 봅니다.)

결국 "함수 중단이나 조건문을 쓰지 말고 타입 힌팅을 써라"가 핵심인 것 같은데 원문을 최대한 살리는 것이 좋을 것 같아 다음과 같이 제안합니다.

"함수 중단, 조건문 대신 초기 변수 선언을 활용하기"

**Comment by FacerAin** [comment]
함수 중단이라는 의미로 해석할 수 있었군요 🔥
참고 링크까지 감사합니다!! 😊😊
