### ISSUE TITLE
[Question 🤔] Introduction 번역 관련

### ISSUE THREAD

**Issue by FacerAin** [EarthCodingLab/clean-code-python#6]
**원문**
Not every principle herein has to be strictly followed, and even fewer will be
universally agreed upon. These are guidelines and nothing more, but they are
ones codified over many years of collective experience by the authors of *Clean
Code*.

**번역 중**
여기에 있는 모든 원칙을 엄격하게 준수해야 하는 것은 아니며, and even fewer will be universally agreed upon. 원칙들은 어디까지나 가이드라인일 뿐이지만, Clean Code의 저자들이 다년간의 경험을 집약해 성문화한 것입니다.

Introduction에서 위 문단을 어떻게 매끄럽게 번역할 수 있을지 궁금합니다.

**Comment by kyc3492** [comment]
'여기에 소개된 원칙들이 절대적인 것은 아니' 라는 뉘앙스를 이어다가 '보편적으로 쓰이고 있는 것들은 더 적다' 라고 얘기하는 느낌인 것 같아요. 원문을 최대한 살린다면 위처럼 될 것 같고 좀 더 의역하면 이렇게 제안해봅니다. 😁

여기에 있는 모든 원칙을 엄격하게 준수해야 하는 것은 아니며, 심지어 일반적으로 준수되고 있는 원칙들은 더 적습니다.

**Comment by kyc3492** [comment]
좀 더 많이 의역하면 이렇게도 될 수 있을 것 같아요.

여기에 있는 모든 원칙을 엄격하게 준수해야 하는 것은 아니며, 심지어 많은 사람들이 일반적으로 준수해야 한다고 동의할만한 원칙들은 훨씬 적을 것입니다.

**Comment by FacerAin** [comment]
말씀해주신 대로 의역하니 문장도 훨씬 자연스럽고, 뜻도 분명해진 것 같아요!! 본문에 반영하겠습니다 😊 감사합니다 :)

"여기에 있는 모든 원칙을 엄격하게 준수해야 하는 것은 아니며, 심지어 많은 사람들이 일반적으로 준수해야 한다고 동의할만한 원칙들은 훨씬 적을 것입니다."
